### ISSUE TITLE
VSCode ESLint problem

### ISSUE THREAD

**Issue by barmac** [camunda/eslint-plugin-camunda-licensed#3]
Often, when I use this plugin with ESLint plugin for VSCode, I struggle with a never ending error. Cf. gif below:

![problem](https://user-images.githubusercontent.com/28307541/53653255-36bbc580-3c4b-11e9-8903-934b769d918e.gif)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

It might be caused by automatic carriage return addition, see git diff below:

<img width="736" alt="screenshot 2019-03-01 at 17 57 39" src="https://user-images.githubusercontent.com/28307541/53653486-ad58c300-3c4b-11e9-8ad4-0fb781e3cd2d.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (4.01GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
django-html|bib|1.3.0
django|big|1.0.0
vscode-styled-jsx|bla|1.0.0
solargraph|cas|0.19.3
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.5.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.9
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|7.0.1
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|7.2.5
vscode-extension-auto-import|mop|1.3.3
python|ms-|2019.2.5433
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
vscode-extension-auto-import|Nuc|1.4.3
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
ruby|reb|0.22.2
code-settings-sync|Sha|3.2.5
gitconfig|sid|2.0.0
js-jsx-snippets|sky|0.3.0
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
bootstrap4-vscode|the|6.0.3
vscode-snippets|the|0.1.3
vsfire|tob|1.4.1
highlight-matching-tag|vin|0.8.6
vscode-react-native|vsm|0.8.0
vscode-import-cost|wix|2.12.0
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>

**Comment by nikku** [comment]
```plain
// given
* file formatted windows style (CRLF)

// when
* linting

// then
* validate with CRLF as line ending
* fix using CRLF
```

**Comment by nikku** [comment]
This is fixed in the upstream `license-header` plugin, version `0.1.2`. We now check / apply the license based on the files line separator as sketched [here](https://github.com/camunda/eslint-plugin-camunda-licensed/issues/3#issuecomment-469196713).

**Comment by nikku** [comment]
Perform a deep update of your project _or_ update `eslint-plugin-camunda-licensed` to `v0.4.1` to fix the issue.

**Comment by barmac** [comment]
Cool, it works!
